# https://taskfile.dev

version: '3'

vars:
  JUPYTER_ARGS: lab --ip 0.0.0.0 --allow-root
  GIT_URI: git@github.com:opensyllabus/catalog-parser.git

env:
  SSH_IP_ADDRESS: "135.181.63.162"
  SSH_KEY_PATH: "../.ssh/id_rsa"

tasks:

  ssh:
    cmds:
      - ssh-add $SSH_KEY_PATH
      - ssh root@$SSH_IP_ADDRESS

  ssh:clone:
    cmds:
      - scp -r $SSH_KEY_PATH root@$SSH_IP_ADDRESS:/root/.ssh/id_rsa
      - scp -r ~/.gitconfig root@$SSH_IP_ADDRESS:/root/.gitconfig
      - ssh root@$SSH_IP_ADDRESS "ssh-keyscan github.com >> ~/.ssh/known_hosts"
      - ssh root@$SSH_IP_ADDRESS "git clone {{.GIT_URI}}"

  ssh:task:
    cmds:
      - ssh root@$SSH_IP_ADDRESS 'sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /bin'
      - scp -r Taskfile.yaml root@$SSH_IP_ADDRESS:/root/Taskfile.yaml

  ssh:aws:
    cmds:
      - ssh root@$SSH_IP_ADDRESS 'apt update'
      - ssh root@$SSH_IP_ADDRESS 'apt install awscli -y'
      - scp -r ~/.aws root@$SSH_IP_ADDRESS:/root/.aws

  poetry:
    cmds:
      - curl -sSL https://install.python-poetry.org | python3 -
      - echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
      - tmux

  jupyter:
    cmds:
      - jupyter {{.JUPYTER_ARGS}}
