# https://taskfile.dev

version: "3"

dotenv: [".env"]

tasks:
  ssh:
    desc: SSH into the remote instance
    cmds:
      - ssh-add $REMOTE_SSH_KEY
      - ssh $REMOTE_ROOT@$SSH_IP_ADDRESS -p $SSH_PORT

  scp:
    desc: Copy a file into the remote instance
    cmds:
      - scp -P $SSH_PORT -r {{.CLI_ARGS}} $REMOTE_ROOT@$SSH_IP_ADDRESS:$REMOTE_HOME/

  scp:down:
    desc: |
      Copy a file from the remote instance
      Example: scp:down -- file.txt
    cmds:
      - scp -P $SSH_PORT -r $REMOTE_ROOT@$SSH_IP_ADDRESS:/{{.CLI_ARGS}} .

  clone:
    desc: Configure git and clone the repo
    cmds:
      - scp -P $SSH_PORT -r $GIT_SSH_KEY $REMOTE_ROOT@$SSH_IP_ADDRESS:$REMOTE_HOME/.ssh/id_rsa
      - scp -P $SSH_PORT -r ~/.gitconfig $REMOTE_ROOT@$SSH_IP_ADDRESS:$REMOTE_HOME/.gitconfig
      - ssh $REMOTE_ROOT@$SSH_IP_ADDRESS -p $SSH_PORT "ssh-keyscan github.com >> ~/.ssh/known_hosts"
      - ssh $REMOTE_ROOT@$SSH_IP_ADDRESS -p $SSH_PORT "git clone $GIT_URI"

  task:
    desc: Install TaskFile and copy over the file
    cmds:
      - ssh $REMOTE_ROOT@$SSH_IP_ADDRESS -p $SSH_PORT 'sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin'
      - task: task:file

  task:file:
    desc: Copy over the default Task file
    cmds:
      - scp -P $SSH_PORT -r $REMOTE_TASK_FILE $REMOTE_ROOT@$SSH_IP_ADDRESS:$REMOTE_HOME/Taskfile.yaml

  apt:
    desc: Update apt and install tools
    cmds:
      - ssh $REMOTE_ROOT@$SSH_IP_ADDRESS -p $SSH_PORT 'apt update'
      - ssh $REMOTE_ROOT@$SSH_IP_ADDRESS -p $SSH_PORT 'apt install git tmux nvtop unzip -y'

  aws:
    desc: Install AWS CLI and configure
    cmds:
      - ssh $REMOTE_ROOT@$SSH_IP_ADDRESS -p $SSH_PORT 'apt update'
      - ssh $REMOTE_ROOT@$SSH_IP_ADDRESS -p $SSH_PORT 'apt install awscli -y'
      - task: aws:config

  aws:config:
    desc: Copy over AWS CLI configuration
    cmds:
      - scp -P $SSH_PORT -r ~/.aws $REMOTE_ROOT@$SSH_IP_ADDRESS:$REMOTE_HOME/.aws

  tunnel:
    desc: Start a SSH tunnel
    cmds:
      - ssh -NL $SSH_TUNNEL_PORT:localhost:$SSH_TUNNEL_PORT $REMOTE_ROOT@$SSH_IP_ADDRESS -p $SSH_PORT
