# https://taskfile.dev

version: '3'

vars:
  JUPYTER_ARGS: lab --ip 0.0.0.0 --allow-root
  GIT_URI: git@github.com:mingiryu/retask.git

env:
  SSH_IP_ADDRESS: "135.181.63.183"
  SSH_KEY_PATH: "../.ssh/id_rsa"

tasks:

  ssh:
    cmds:
      - ssh root@$SSH_IP_ADDRESS

  ssh:add:
    cmds:
      - ssh-add $SSH_KEY_PATH

  ssh:github:
    cmds:
      - ssh root@$SSH_IP_ADDRESS "ssh-keyscan github.com >> ~/.ssh/known_hosts"

  ssh:clone:
    cmds:
      - ssh root@$SSH_IP_ADDRESS "git clone {{.GIT_URI}}"

  ssh:task:
    cmds:
      - ssh root@$SSH_IP_ADDRESS 'sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /bin'

  scp:ssh:
    cmds:
      - scp -r $SSH_KEY_PATH root@$SSH_IP_ADDRESS:/root/.ssh/id_rsa

  scp:git:
    cmds:
      - scp -r ~/.gitconfig root@$SSH_IP_ADDRESS:/root/.gitconfig

  scp:aws:
    cmds:
      - scp -r ~/.aws root@$SSH_IP_ADDRESS:/root/.aws

  scp:task:
    cmds:
      - scp -r Taskfile.yaml root@$SSH_IP_ADDRESS:/root/Taskfile.yaml
      
  jupyter:
    cmds:
      - jupyter {{.JUPYTER_ARGS}}
